eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liaojiangtao/SpringCloudConfig.git
          username: 151280368@qq.com
          password: Liao12#$
  rabbitmq:
    host: 47.98.111.83
    port: 5672
    username: root
    password: root
    virtual-host: my_vhost
server:
  port: 9510
management:
  endpoints:
    web:
      exposure:
        include: "*"